# Generated by Django 5.0.4 on 2024-06-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
