# Generated by Django 5.0.4 on 2024-06-08 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'permissions': [('modifier_images', 'Peut modifier les images')]},
        ),
    ]
